@echo off
:: ============================================================
:: gitpush.bat — CPS Git Push
:: Generated by Claude. Overwritten each session on "gitpush".
:: StreamDeck target: this file (fixed path).
:: ============================================================

set COWORK=H:\Claude Cowork\Projects\Claude Project System
set GIT=H:\Github\claude-project-system
set LOG=%COWORK%\Output\gitpush-log.txt

echo [%DATE% %TIME%] ===== GIT PUSH START ===== > "%LOG%"

echo [CPS] Syncing files to git clone...
echo [%DATE% %TIME%] Syncing files... >> "%LOG%"

robocopy "%COWORK%" "%GIT%" CLAUDE.md /IS /IT /NFL /NDL >> "%LOG%"
robocopy "%COWORK%\Runtime"       "%GIT%\Runtime"       /MIR /NFL /NDL >> "%LOG%"
robocopy "%COWORK%\Reference"     "%GIT%\Reference"     /MIR /NFL /NDL >> "%LOG%"
robocopy "%COWORK%\Documentation" "%GIT%\Documentation" /MIR /NFL /NDL >> "%LOG%"
robocopy "%COWORK%\Skills"        "%GIT%\Skills"        /MIR /NFL /NDL >> "%LOG%"
if exist "%COWORK%\Patches" (
    robocopy "%COWORK%\Patches" "%GIT%\Patches" /MIR /NFL /NDL >> "%LOG%"
)

echo [CPS] Committing...
echo [%DATE% %TIME%] Committing... >> "%LOG%"

cd /d %GIT%
git pull origin main >> "%LOG%" 2>&1
git add -A >> "%LOG%" 2>&1
git commit -m "SESSION_COMMIT_MESSAGE_PLACEHOLDER" >> "%LOG%" 2>&1
git push origin main >> "%LOG%" 2>&1

echo [%DATE% %TIME%] ===== GIT PUSH COMPLETE ===== >> "%LOG%"
echo [CPS] Done. Log: %LOG%
